/**
 * withGradleJvmArgs — raise the Gradle daemon JVM memory in the *generated* android project.
 *
 * Why this is a config plugin and not a workflow `sed`/`GRADLE_OPTS`
 * ----------------------------------------------------------------
 * `android/` is git-ignored and regenerated by `expo prebuild --clean` on every CI run and
 * every local `prepare-android-studio.sh` run, so anything written into it by hand is lost.
 * Expo's own bare template ships `org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m`,
 * which is not enough for this app: the release-only Android Lint gate
 * (`:app:lintVitalAnalyzeRelease`, run automatically as part of `assembleRelease`) lints
 * every native module (expo, expo-constants, reanimated, onesignal, track-player, …) and
 * dies with `java.lang.OutOfMemoryError: Java heap space` / `Metaspace` on a 2 GiB daemon
 * (see run 35212151391). A config plugin runs *inside* prebuild, so the value survives
 * `--clean` and is applied identically for CI (`assembleRelease`), `expo run:android` and
 * local release builds.
 *
 * Note on GRADLE_OPTS: it configures the Gradle *client*, while `org.gradle.jvmargs` in
 * gradle.properties configures the *daemon* (and takes precedence). The daemon is where
 * lint/codegen runs, so this is the correct lever.
 *
 * Related: `scripts/prepare-android-studio.sh` intentionally overrides this value locally
 * with its own managed block (4 GiB / 1 GiB) — that is fine, both are above the template.
 *
 * Keep the CI guard step in `.github/workflows/release.yml` in sync with VALUES below: it
 * fails the build if prebuild ever stops applying these args.
 */

const { withGradleProperties } = require('expo/config-plugins')

// Heap for the Gradle daemon: Compose + AGP + Lint analysis of ~50 modules.
const GRADLE_JVMARGS = '-Xmx6144m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8'

// Gradle properties this plugin owns. Anything listed here is replaced (never duplicated):
// `properties-parser` keeps a list of items, and a second `org.gradle.jvmargs` would make
// the effective value depend on file order.
const MANAGED_PROPERTIES = ['org.gradle.jvmargs']

function upsertProperty(properties, key, value) {
  const existing = properties.find((item) => item.type === 'property' && item.key === key)
  if (existing) {
    existing.value = value
  } else {
    properties.push({ type: 'property', key, value })
  }
}

module.exports = function withGradleJvmArgs(config) {
  return withGradleProperties(config, (cfg) => {
    // Defensive: drop any duplicate the template (or another plugin) may have produced.
    cfg.modResults = cfg.modResults.filter(
      (item) => !(item.type === 'property' && MANAGED_PROPERTIES.includes(item.key)),
    )
    upsertProperty(cfg.modResults, 'org.gradle.jvmargs', GRADLE_JVMARGS)
    return cfg
  })
}

module.exports.GRADLE_JVMARGS = GRADLE_JVMARGS
