#!/usr/bin/env bash
#
# prepare-android-studio.sh — make the generated `android/` project buildable from
# Android Studio *and* from the command line on this machine.
#
# Why this exists
# ---------------
# `android/` is git-ignored and regenerated by `expo prebuild --platform android --clean`,
# so nothing machine-specific can be committed. But the freshly generated project is not
# directly openable in Android Studio:
#
#   1. Gradle daemon JVM — `gradle/gradle-daemon-jvm.properties` pins the daemon to a JDK.
#      Android Studio's bundled JBR is JDK 25, and JDK 24+ prints
#      "WARNING: A restricted method in java.lang.System has been called"; AGP's
#      `GeneratePrefabPackages` reads that warning out of its configure log and fails the
#      task with `IllegalStateException: WARNING: A restricted method ...`.
#      The daemon JVM criteria file *wins over* `org.gradle.java.home`, so the only reliable
#      lever is the criteria file itself → we pin it to a JDK AGP can actually run on (17/21).
#      Pinning it also means Studio's own "Gradle JDK" setting is irrelevant: the launcher
#      may be JDK 25 while the daemon runs on 17/21 (verified).
#   2. ABIs — Studio configures every ABI in `reactNativeArchitectures` (all four by default)
#      which makes IDE builds slow. `expo run:android` narrows this to the host ABI; we do
#      the same so "Run" in the IDE is fast, and the value can be overridden.
#   3. SDK location — `local.properties` is not produced by prebuild.
#   4. `node` on PATH — the generated Gradle scripts shell out to `node` (settings.gradle,
#      app/build.gradle and the compiled expo/RN Gradle plugins hard-code the name "node").
#      Android Studio launched from the Dock/Finder inherits launchd's minimal PATH
#      (/usr/bin:/bin:/usr/sbin:/sbin) and fails with `Cannot run program "node"`.
#      There is no Gradle property for this — node has to be on the daemon's PATH, so the
#      supported ways are: launch Studio with scripts/open-android-studio.sh (recommended),
#      or opt in to the GUI PATH agent with --install-gui-path.
#
# Safety
# ------
# The script only ever writes inside the git-ignored `android/` directory, plus
# ~/Library/LaunchAgents when you explicitly pass --install-gui-path. It never touches
# tracked files and never embeds a hard-coded JDK/node/SDK path in anything committed —
# every path is auto-detected at runtime.
#
# Usage
# -----
#   scripts/prepare-android-studio.sh                     # prebuild + apply local settings
#   scripts/prepare-android-studio.sh --skip-prebuild     # re-apply settings only
#   scripts/prepare-android-studio.sh --abis=all          # keep all four ABIs
#   scripts/prepare-android-studio.sh --jdk-major=21      # force JDK 21 for the daemon
#   scripts/prepare-android-studio.sh --verify            # ... and run a sync-equivalent task
#   scripts/prepare-android-studio.sh --install-gui-path # make Dock/Finder launches work too
#   scripts/prepare-android-studio.sh --uninstall-gui-path
#   scripts/prepare-android-studio.sh --help
#
# Idempotent: re-running replaces the managed block instead of appending to it.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ANDROID_DIR="$ROOT_DIR/android"

START_MARKER='# >>> RAW Radio local dev overrides (managed by scripts/prepare-android-studio.sh) >>>'
END_MARKER='# <<< RAW Radio local dev overrides <<<'

GUI_AGENT_LABEL='ru.rawradio.gradle-path'
GUI_AGENT_PLIST="$HOME/Library/LaunchAgents/$GUI_AGENT_LABEL.plist"

RUN_PREBUILD=1
RUN_VERIFY=0
INSTALL_GUI_PATH=0
UNINSTALL_GUI_PATH=0
JDK_MAJOR_PREFERENCE="${RAW_RADIO_GRADLE_JDK_MAJOR:-17}"
ABIS="${RAW_RADIO_ANDROID_ABIS:-}"

# ──────────────────────────────────────────────────────────────────────────────
# Output helpers
# ──────────────────────────────────────────────────────────────────────────────

if [ -t 1 ] && [ -z "${NO_COLOR:-}" ]; then
  C_RESET=$'\033[0m'; C_DIM=$'\033[2m'; C_BOLD=$'\033[1m'
  C_RED=$'\033[31m'; C_GREEN=$'\033[32m'; C_YELLOW=$'\033[33m'; C_BLUE=$'\033[34m'
else
  C_RESET=''; C_DIM=''; C_BOLD=''; C_RED=''; C_GREEN=''; C_YELLOW=''; C_BLUE=''
fi

info()  { printf '%s\n' "${C_BLUE}·${C_RESET} $*"; }
ok()    { printf '%s\n' "${C_GREEN}✔${C_RESET} $*"; }
warn()  { printf '%s\n' "${C_YELLOW}!${C_RESET} $*" >&2; }
die()   { printf '%s\n' "${C_RED}✖ $*${C_RESET}" >&2; exit 1; }
hdr()   { printf '\n%s\n' "${C_BOLD}$*${C_RESET}"; }

usage() {
  sed -n '2,60p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
  exit 0
}

# ──────────────────────────────────────────────────────────────────────────────
# Argument parsing
# ──────────────────────────────────────────────────────────────────────────────

for arg in "$@"; do
  case "$arg" in
    --help|-h)            usage ;;
    --skip-prebuild)      RUN_PREBUILD=0 ;;
    --verify)             RUN_VERIFY=1 ;;
    --install-gui-path)   INSTALL_GUI_PATH=1 ;;
    --uninstall-gui-path) UNINSTALL_GUI_PATH=1 ;;
    --jitless)            ;; # reserved / ignored
    --abis=*)             ABIS="${arg#--abis=}" ;;
    --jdk-major=*)        JDK_MAJOR_PREFERENCE="${arg#--jdk-major=}" ;;
    *) die "Unknown option: $arg (try --help)" ;;
  esac
done

case "$JDK_MAJOR_PREFERENCE" in
  17|21) ;;
  *) die "--jdk-major must be 17 or 21 (got '$JDK_MAJOR_PREFERENCE')." ;;
esac

# ──────────────────────────────────────────────────────────────────────────────
# Detection helpers
# ──────────────────────────────────────────────────────────────────────────────

# Major version of the JDK at $1, or empty when it is not a usable JDK home.
jdk_major_of() {
  local home="$1"
  [ -x "$home/bin/java" ] || return 1
  "$home/bin/java" -version 2>&1 | head -n 1 | sed -n 's/.*version "\([0-9][0-9]*\).*/\1/p'
}

# Java >= 9 reports "17"/"21"; legacy 1.8 reports "1" — anything but 17/21 is unusable here.
is_supported_major() {
  case "$1" in 17|21) return 0 ;; *) return 1 ;; esac
}

detect_jdks() {
  # Prints "<major> <home>" for every supported JDK found, best first.
  local candidates="" home major out=""

  # 1. Explicit override always wins.
  [ -n "${RAW_RADIO_GRADLE_JDK_HOME:-}" ] && candidates="$candidates ${RAW_RADIO_GRADLE_JDK_HOME}"

  # 2. macOS java_home (fast + authoritative when present).
  if [ -x /usr/libexec/java_home ]; then
    for v in "$JDK_MAJOR_PREFERENCE" 17 21; do
      home="$(/usr/libexec/java_home -v "$v" 2>/dev/null || true)"
      [ -n "$home" ] && candidates="$candidates $home"
    done
  fi

  # 3. Well-known install roots (system, per-user, Homebrew, Linux distros).
  local glob_root
  for glob_root in \
    /Library/Java/JavaVirtualMachines/*/Contents/Home \
    "$HOME/Library/Java/JavaVirtualMachines"/*/Contents/Home \
    /opt/homebrew/opt/openjdk@*/libexec/openjdk.jdk/Contents/Home \
    /usr/local/opt/openjdk@*/libexec/openjdk.jdk/Contents/Home \
    /usr/lib/jvm/* \
    /usr/lib/jvm/*/Contents/Home
  do
    [ -d "$glob_root" ] && candidates="$candidates $glob_root"
  done

  # 4. Studio's bundled runtime is the culprit, not the fix — only accept it if it is 17/21.
  candidates="$candidates /Applications/Android Studio.app/Contents/jbr/Contents/Home"

  # Score → "preferred major first, then the other, then dedupe".
  local scored=""
  for home in $candidates; do
    major="$(jdk_major_of "$home" || true)"
    is_supported_major "${major:-}" || continue
    if [ "$major" = "$JDK_MAJOR_PREFERENCE" ]; then
      scored="$scored 0|$major|$home"
    else
      scored="$scored 1|$major|$home"
    fi
  done

  [ -n "$scored" ] || return 1

  local seen_major=""
  local entry m
  for entry in $(printf '%s\n' $scored | sort -t'|' -k1,1n -k2,2n); do
    m="$(printf '%s' "$entry" | cut -d'|' -f2)"
    case " $seen_major " in *" $m "*) continue ;; esac
    seen_major="$seen_major $m"
    out="$out$m $(printf '%s' "$entry" | cut -d'|' -f3)
"
  done
  printf '%s' "$out"
}

detect_all_jdk_homes() {
  # Every 17/21 home we can see — used for org.gradle.java.installations.paths.
  local found=""
  local glob_root home major
  for glob_root in \
    /Library/Java/JavaVirtualMachines/*/Contents/Home \
    "$HOME/Library/Java/JavaVirtualMachines"/*/Contents/Home \
    /opt/homebrew/opt/openjdk@*/libexec/openjdk.jdk/Contents/Home \
    /usr/local/opt/openjdk@*/libexec/openjdk.jdk/Contents/Home \
    /usr/lib/jvm/* \
    /usr/lib/jvm/*/Contents/Home
  do
    [ -d "$glob_root" ] || continue
    major="$(jdk_major_of "$glob_root" || true)"
    is_supported_major "${major:-}" || continue
    case " $found " in *" $glob_root "*) continue ;; esac
    found="$found $glob_root"
  done
  printf '%s' "${found# }"
}

detect_node() {
  local candidate
  if candidate="$(command -v node 2>/dev/null)" && [ -x "$candidate" ]; then
    printf '%s' "$candidate"; return 0
  fi
  # nvm / Homebrew / system fallbacks — Studio launched from the Dock has none of these
  # on PATH, but they exist on disk and we can hand the absolute path to the wrapper.
  local glob
  for glob in \
    "$HOME/.nvm/versions/node"/*/bin/node \
    /opt/homebrew/bin/node \
    /usr/local/bin/node \
    /usr/bin/node
  do
    if [ -x "$glob" ]; then printf '%s' "$glob"; return 0; fi
  done
  return 1
}

detect_android_sdk() {
  local candidate
  for candidate in \
    "${ANDROID_HOME:-}" \
    "${ANDROID_SDK_ROOT:-}" \
    "$HOME/Library/Android/sdk" \
    "$HOME/Android/Sdk" \
    "$HOME/Android/sdk" \
    /usr/local/share/android-sdk \
    /opt/android-sdk
  do
    if [ -n "$candidate" ] && [ -d "$candidate" ]; then printf '%s' "$candidate"; return 0; fi
  done
  return 1
}

# Prepend directory $1 to PATH when it is not already there (no duplicates).
path_prepend() {
  local dir="$1"
  [ -n "$dir" ] || return 0
  case ":$PATH:" in
    *":$dir:"*) ;;
    *) PATH="$dir:$PATH"; export PATH ;;
  esac
}

# ──────────────────────────────────────────────────────────────────────────────
# GUI PATH agent (opt-in) — makes Dock/Finder-launched Android Studio see `node`
# ──────────────────────────────────────────────────────────────────────────────

gui_agent_path_value() {
  local existing
  existing="$(launchctl getenv PATH 2>/dev/null || true)"
  [ -n "$existing" ] || existing='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
  local node_dir
  node_dir="$(dirname "$NODE_BIN")"
  case ":$existing:" in
    *":$node_dir:"*) printf '%s' "$existing" ;;
    *) printf '%s' "$node_dir:$existing" ;;
  esac
}

install_gui_agent() {
  hdr 'GUI PATH agent (Dock / Finder launches)'
  if [ ! -d "$HOME/Library/LaunchAgents" ]; then
    mkdir -p "$HOME/Library/LaunchAgents"
  fi

  local path_value
  path_value="$(gui_agent_path_value)"

  cat > "$GUI_AGENT_PLIST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/prepare-android-studio.sh — safe to delete.
     Makes launchd-launched GUI apps (Dock, Finder, Spotlight) inherit a PATH that
     contains node, which the generated Gradle scripts require. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$GUI_AGENT_LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/launchctl</string>
    <string>setenv</string>
    <string>PATH</string>
    <string>$path_value</string>
  </array>
  <key>RunAtLoad</key>
  <true/>
</dict>
</plist>
PLIST

  plutil -lint "$GUI_AGENT_PLIST" >/dev/null 2>&1 || die "generated plist is invalid: $GUI_AGENT_PLIST"

  # Idempotent (re)load: bootout/bootstrap on modern macOS, unload/load as fallback.
  launchctl bootout "gui/$(id -u)/$GUI_AGENT_LABEL" >/dev/null 2>&1 || true
  if ! launchctl bootstrap "gui/$(id -u)" "$GUI_AGENT_PLIST" >/dev/null 2>&1; then
    launchctl unload "$GUI_AGENT_PLIST" >/dev/null 2>&1 || true
    launchctl load "$GUI_AGENT_PLIST" >/dev/null 2>&1 || warn "could not load $GUI_AGENT_LABEL"
  fi

  # Apply immediately for apps launched from now on (no logout needed).
  launchctl setenv PATH "$path_value" >/dev/null 2>&1 || true

  ok "GUI PATH agent installed: $GUI_AGENT_PLIST"
  info "PATH for GUI apps: $path_value"
  warn "Already-running applications (including Android Studio) keep their old PATH — quit"
  warn "and relaunch Android Studio after installing this."
}

uninstall_gui_agent() {
  hdr 'GUI PATH agent'
  if [ -f "$GUI_AGENT_PLIST" ]; then
    launchctl bootout "gui/$(id -u)/$GUI_AGENT_LABEL" >/dev/null 2>&1 \
      || launchctl unload "$GUI_AGENT_PLIST" >/dev/null 2>&1 || true
    rm -f "$GUI_AGENT_PLIST"
    ok "removed $GUI_AGENT_PLIST"
  else
    info "no GUI PATH agent installed"
  fi
}

# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

hdr 'RAW Radio — prepare android/ for Android Studio'

# --- node (needed even to run expo prebuild) --------------------------------
NODE_BIN="$(detect_node || true)"
[ -n "$NODE_BIN" ] || die "node not found. Install Node.js (see README) and re-run."
path_prepend "$(dirname "$NODE_BIN")"
ok "node: $NODE_BIN ($("$NODE_BIN" --version))"

# --- JDK --------------------------------------------------------------------
JDK_TABLE="$(detect_jdks || true)"
if [ -z "$JDK_TABLE" ]; then
  printf '%s\n' "${C_RED}✖ No JDK 17 or 21 found.${C_RESET}" >&2
  cat >&2 <<'EOF'

  Android Studio's bundled runtime (JDK 25) cannot run AGP's prefab tasks on this
  project — JDK 24+ trips GeneratePrefabPackages. Install a JDK 17 (same as CI) or 21:

    brew install --cask temurin@17
    # or: brew install --cask zulu@17
    # or: brew install openjdk@21

  Then re-run this script (it auto-detects the new JDK).
EOF
  exit 1
fi

JDK_MAJOR="$(printf '%s' "$JDK_TABLE" | head -n 1 | cut -d' ' -f1)"
JDK_HOME="$(printf '%s' "$JDK_TABLE" | head -n 1 | cut -d' ' -f2)"
ok "Gradle daemon JDK: $JDK_MAJOR ($JDK_HOME)"

JDK_INSTALLATIONS="$(detect_all_jdk_homes || true)"

# --- Android SDK ------------------------------------------------------------
ANDROID_SDK="$(detect_android_sdk || true)"
if [ -n "$ANDROID_SDK" ]; then
  ok "Android SDK: $ANDROID_SDK"
else
  warn "Android SDK not found — Android Studio will ask for it on first sync."
  warn "Set ANDROID_HOME (or install via Studio → SDK Manager) and re-run."
fi

# --- ABI selection ----------------------------------------------------------
if [ -z "$ABIS" ]; then
  case "$(uname -m)" in
    arm64|aarch64) ABIS='arm64-v8a' ;;   # Apple Silicon: device + emulator are arm64-v8a
    x86_64|amd64)  ABIS='x86_64' ;;      # Intel: emulator is x86_64
    *)             ABIS='arm64-v8a,armeabi-v7a' ;;
  esac
fi
case "$ABIS" in
  all) ABIS='armeabi-v7a,arm64-v8a,x86,x86_64' ;;
esac

# --- prebuild ---------------------------------------------------------------
if [ "$RUN_PREBUILD" -eq 1 ]; then
  hdr 'Regenerating android/ (expo prebuild --clean)'
  [ -d "$ROOT_DIR/node_modules" ] || die "node_modules missing — run 'npm ci' in $ROOT_DIR first."
  if [ -x "$ROOT_DIR/node_modules/.bin/expo" ]; then
    EXPO_CMD="$ROOT_DIR/node_modules/.bin/expo"
  else
    EXPO_CMD="npx expo"
  fi
  ( cd "$ROOT_DIR" && EXPO_NO_TELEMETRY=1 $EXPO_CMD prebuild --platform android --clean )
  ok "android/ regenerated"
else
  [ -d "$ANDROID_DIR" ] || die "android/ does not exist — drop --skip-prebuild the first time."
  info "skipping prebuild (--skip-prebuild)"
fi

# --- guard: is android/ still the generated project? ------------------------
[ -f "$ANDROID_DIR/settings.gradle" ] || die "$ANDROID_DIR/settings.gradle missing — prebuild failed?"
[ -f "$ANDROID_DIR/gradle.properties" ] || die "$ANDROID_DIR/gradle.properties missing — prebuild failed?"

# ── 1. Gradle daemon JVM criteria ────────────────────────────────────────────
# THIS is the actual fix for `IllegalStateException: WARNING: A restricted method
# in java.lang.System has been called`. It outranks org.gradle.java.home.
DAEMON_JVM_FILE="$ANDROID_DIR/gradle/gradle-daemon-jvm.properties"
mkdir -p "$(dirname "$DAEMON_JVM_FILE")"
cat > "$DAEMON_JVM_FILE" <<EOF
# Generated by scripts/prepare-android-studio.sh (machine-local, never committed).
#
# Pins the Gradle *daemon* JVM. JDK 24+ makes AGP's GeneratePrefabPackages fail with
# 'IllegalStateException: WARNING: A restricted method in java.lang.System has been
# called', and Android Studio's bundled JBR is JDK 25 — so the daemon must not use it.
# Daemon JVM criteria take precedence over org.gradle.java.home, which is why the pin
# lives here and not in gradle.properties.
#
# CI does not use this file: it regenerates android/ and runs on Temurin 17.
toolchainVersion=$JDK_MAJOR
EOF
ok "daemon JVM pinned to JDK $JDK_MAJOR ($DAEMON_JVM_FILE)"

# ── 2. Local gradle.properties overrides ─────────────────────────────────────
GP="$ANDROID_DIR/gradle.properties"
GP_TMP="$GP.raw-radio.tmp"
JVMARGS='-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8'

GP_START="$START_MARKER" GP_END="$END_MARKER" \
GP_JVMARGS="$JVMARGS" GP_ABIS="$ABIS" GP_JDKS="$JDK_INSTALLATIONS" \
awk '
  BEGIN { inblock = 0 }
  $0 == ENVIRON["GP_START"] { inblock = 1; next }
  $0 == ENVIRON["GP_END"]   { inblock = 0; next }
  inblock { next }
  # drop the generated single-value lines — the managed block below is authoritative
  /^[[:space:]]*#?[[:space:]]*org\.gradle\.jvmargs=/ { next }
  /^[[:space:]]*#?[[:space:]]*reactNativeArchitectures=/ { next }
  { print }
' "$GP" > "$GP_TMP"

{
  printf '\n%s\n' "$START_MARKER"
  printf '%s\n' '# Machine-local values written by scripts/prepare-android-studio.sh.'
  printf '%s\n' '# `expo prebuild --clean` wipes android/ — re-run that script to restore them.'
  if [ -n "$JDK_INSTALLATIONS" ]; then
    printf 'org.gradle.java.installations.paths=%s\n' "$JDK_INSTALLATIONS"
  fi
  printf '%s\n' '# Never let Gradle silently download a JDK we do not want as the daemon.'
  printf '%s\n' 'org.gradle.java.installations.auto-download=false'
  printf 'org.gradle.jvmargs=%s\n' "$JVMARGS"
  printf '%s\n' '# ABI list for IDE builds. Studio otherwise configures all four ABIs (slow, and the'
  printf '%s\n' '# 4-ABI debug APK is ~226 MB). Matches what `expo run:android` passes on the CLI.'
  printf 'reactNativeArchitectures=%s\n' "$ABIS"
  printf '%s\n' "$END_MARKER"
} >> "$GP_TMP"

mv "$GP_TMP" "$GP"
ok "gradle.properties overrides applied (ABIs: $ABIS)"

# ── 3. local.properties (SDK location) ───────────────────────────────────────
if [ -n "$ANDROID_SDK" ]; then
  LP="$ANDROID_DIR/local.properties"
  # Only touch the sdk.dir line, so any extra keys a tool added survive.
  if [ -f "$LP" ]; then
    grep -v '^[[:space:]]*sdk\.dir=' "$LP" > "$LP.tmp" 2>/dev/null || : > "$LP.tmp"
  else
    : > "$LP.tmp"
  fi
  {
    printf '%s\n' '## Machine-local SDK location — written by scripts/prepare-android-studio.sh.'
    printf '%s\n' '## Not for version control.'
    printf 'sdk.dir=%s\n' "$ANDROID_SDK"
  } >> "$LP.tmp"
  mv "$LP.tmp" "$LP"
  ok "local.properties → sdk.dir=$ANDROID_SDK"
fi

# ── 4. Optional GUI PATH agent ───────────────────────────────────────────────
if [ "$UNINSTALL_GUI_PATH" -eq 1 ]; then
  uninstall_gui_agent
elif [ "$INSTALL_GUI_PATH" -eq 1 ]; then
  [ "$(uname -s)" = "Darwin" ] || warn "--install-gui-path is macOS-only; ignoring."
  [ "$(uname -s)" = "Darwin" ] && install_gui_agent
fi

# ── 5. Optional verification ─────────────────────────────────────────────────
if [ "$RUN_VERIFY" -eq 1 ]; then
  hdr 'Verification (Gradle client + configuration)'
  ( cd "$ANDROID_DIR" && ./gradlew --version 2>&1 | grep -E 'Gradle |Launcher JVM|Daemon JVM' ) || true
  info 'running :app:tasks (the same configuration work a Studio sync performs)'
  ( cd "$ANDROID_DIR" && ./gradlew :app:tasks --offline >/dev/null 2>&1 ) \
    && ok "Gradle configuration succeeded with daemon JDK $JDK_MAJOR" \
    || die "Gradle configuration failed — re-run 'cd android && ./gradlew :app:tasks' to see why."
fi

# ── Summary ──────────────────────────────────────────────────────────────────
hdr 'Done'
cat <<EOF
  JDK for Gradle daemon : $JDK_MAJOR
  JDK home              : $JDK_HOME
  node                  : $NODE_BIN
  SDK                   : ${ANDROID_SDK:-<not found>}
  ABIs                  : $ABIS

Next steps in Android Studio:
  1. Launch it so it sees node:   scripts/open-android-studio.sh
     (Dock/Finder launches need '--install-gui-path' — see docs/DEVELOPMENT.md)
  2. Open the folder:             $ANDROID_DIR
  3. Wait for "Gradle sync" to finish — it should succeed as-is.
  4. Settings → Build, Execution, Deployment → Build Tools → Gradle → "Gradle JDK"
     only affects the launcher; the daemon is pinned to JDK $JDK_MAJOR, so leaving it
     on the embedded JDK is fine.
EOF
